#
# Copyright (C) 2020 Tomasz Walczyk
#
# This software may be modified and distributed under the terms
# of the MIT license. See the LICENSE file for details.
#
###########################################################

name: CI
on:
  push:
    branches:
    - master
    paths-ignore:
    - LICENSE
    - README.md
  pull_request:
    branches:
    - master
    paths-ignore:
    - LICENSE
    - README.md
jobs:
  test_linux:
    name: Test On Linux
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
      - name: Install Dependencies
        run: sudo apt-get install xorriso
      - name: Create Debian ISO
        run: bash create-debian-iso.bash
  test_macos:
    name: Test On MacOS
    runs-on: macOS-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
      - name: Install Dependencies
        run: brew install xorriso
      - name: Create Debian ISO
        run: bash create-debian-iso.bash
  test_windows:
    name: Test On Windows
    runs-on: windows-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
      - name: Create Debian ISO
        run: powershell .\CreateDebianISO.ps1
