#
# Copyright (C) 2020-2021 Tomasz Walczyk
#
# This software may be modified and distributed under the terms
# of the MIT license. See the LICENSE file for details.
#
############################################################

name: CI
on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Define env name'
        required: true
        default: 'prod'
      branch:
        description: 'Define branch name'
        required: true
        default: 'master'
jobs:
  test_on_linux:
    name: Test On Linux
    needs: check_version
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
      - name: Generate CMake Project
        run: |
          env | sort
